spring:
  application:
    name: nwtea-cloud-user
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${myConfig.eurekaServer.port}/eureka
myConfig:
  eurekaServer:
    port: 8761